image: aerospike/aerospike-server
replicaCount: 1
storageClassName: gp2
storage: 8Gi
config: |
  service {
    cluster-name docker
  }

  logging {
    # Send log messages to stdout
    console {
      context any info
    }
  }

  network {
    service {
      address any
      port 3000

      # Uncomment the following to set the 'access-address' parameter to the
      # IP address of the Docker host. This will the allow the server to correctly
      # publish the address which applications and other nodes in the cluster to
      # use when addressing this node.
      # access-address <IPADDR>
    }

    heartbeat {
      # mesh is used for environments that do not support multicast
      mode mesh
      address local
      port 3002
      interval 150
      timeout 10
    }

    fabric {
      # Intra-cluster communication port (migrates, replication, etc)
      # default to same address in 'service'
      address local
      port 3001
    }
  }

  namespace test {
    default-ttl 30d # use 0 to never expire/evict.
    nsup-period 120
    replication-factor 1
    storage-engine device {
      # For 'storage-engine memory' with 'device' or 'file' backing, we
      # recommend having multiple devices (eight is recommended). One is used
      # here for backward compatibility.
      file /opt/aerospike/data/test.dat
      filesize 4G
      read-page-cache true
    }
  }

  namespace main {
    default-ttl 30d
    nsup-period 120
    replication-factor 1
    storage-engine device {
      file /opt/aerospike/data/main.dat
      filesize 4G
      read-page-cache true
    }
  }
  