apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - port: 3000
    name: client
  - port: 3001
    name: fabric
  - port: 3002
    name: heartbeat
  - port: 3003
    name: info
  selector:
    app: {{ .Release.Name }}
