apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
      annotations:
        config-checksum: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: {{ .Release.Name }}-init
        image: busybox
        command:
        - sh
        - -c
        - >
          cp /config/aerospike.conf /etc/aerospike/aerospike.conf;
          echo "Configuration file copied to /etc/aerospike/aerospike.conf";
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: config
          mountPath: /etc/aerospike
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image }}:{{ .Chart.AppVersion }}
        ports:
        - containerPort: 3000
        - containerPort: 3001
        - containerPort: 3002
        - containerPort: 3003
        volumeMounts:
        - name: data
          mountPath: /opt/aerospike/data
        - name: config
          mountPath: /etc/aerospike
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.storage }}
      storageClassName: {{ .Values.storageClassName }}
  - metadata:
      name: config
    spec:
      accessModes: 
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: {{ .Values.storageClassName }}
